cc_test(
  name = "generator_test",
  size = "small",
  srcs = ["generator_test.cpp", "generator.cpp"],
  deps = ["@com_google_googletest//:gtest_main"],
)

cc_binary(
  name = "generator",
  srcs = ["generator.cpp"],
)
