load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/5b7fd63d6d69f1754d5f3be956949484ebac06d5.zip"],
  strip_prefix = "googletest-5b7fd63d6d69f1754d5f3be956949484ebac06d5",
)
